### ISSUE TITLE
Code related feedback

### ISSUE THREAD

**Issue by jigneshnakrani088** [dinakajoy/elementor_tab_widget#2]
- [x] Already enqueued the [JS/CSS](https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/tab-widget.php#L66) in [widgets-loader.php] 
     - [ ] This is a more robust way to add JS for elementor widget https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/
     - [x] `wp_rand()` Better to use plugin/js version or `file modified time string` instead of random string every time.

 - [x] (https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/widgets-loader.php#L148)
     - [ ] Widget dependant scripts/stypes should be loaded only when the widget is being used.
 - [x] Typo:: Same titled controls - https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/tab-widget.php#L603-L653
 - [ ] Found separate sections for mobile and desktop version, should be better if handle with CSS with a single.
 - [ ] Should use `get_render_attribute_string()` instead of manually adding attributes ref: https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/tab-widget.php#L918
 - [ ] Found direct use of $_GET https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/widgets-loader.php#L233
 - [x] Not able to edit Accordion title `WHAT ARE YOUR DEALERSHIP'S BIGGEST CHALLENGES`, Nor find from where it's added (Code OR control)

**Comment by dinakajoy** [comment]
This is a more robust way to add JS for elementor widget https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/ - I tried this for long but the click event for the render function won't work. I would learn more about this.

Widget dependent scripts/styles should be loaded only when the widget is being used. - Tried adding it as a dependency but it causes a flash when the styles are applied after loading the content. So enqueueing it it during initialization was preferred for better experience

Found separate sections for mobile and desktop version, should be better if handle with CSS with a single - Tab was used for large devices and accordion for mobile. Making the style for accordion to render as a widget got so messy. Keeping them separate and rendering each accordingly seemed pretty straight

Should use get_render_attribute_string() instead of manually adding attributes ref: https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/tab-widget.php#L918 - This adds extra double quotes and for some reasons, the styles won't apply. I will still research more 

 Found direct use of $_GET https://github.com/dinakajoy/elementor_tab_widget/blob/develop/elementor-widgets/widgets-loader.php#L233 - Using this was the bet way to retrieve that function, the other available method works only on admin. I silenced phpcs as adviced here - https://github.com/WordPress/WordPress-Coding-Standards/issues/1878
